'use strict';

/* ════════════════════════════════════════════════
   D2C AI Growth Suite — Frontend Application v2
   ════════════════════════════════════════════════ */

// ── State ─────────────────────────────────────────
const state = {
  slug:   null,
  key:    null,
  demo:   false,
  config: null,
  cache:  {},
  agencyKey: null,
  sseSource: null,
  feedItems: [],
  demoFeedTimer: null,
};

// ── Category manifest ─────────────────────────────
const CATEGORIES = [
  {
    id: 'acquire', label: 'Acquire', cls: 'cat-acquire',
    workflows: [
      { id: 'A-01', name: 'Smart Lead Capture',    desc: 'AI-scores leads in real time and routes hot prospects to Slack & Calendly.' },
      { id: 'A-02', name: 'Outreach Sequencer',    desc: 'Personalised 3-step cold email cadences generated by GPT-4.' },
      { id: 'A-03', name: 'Instagram DM Bot',      desc: 'Converts story replies & DM enquiries into qualified leads automatically.' },
      { id: 'A-04', name: 'Referral Engine',       desc: 'Auto-triggers referral invites post-purchase and tracks conversions.' },
    ],
  },
  {
    id: 'convert', label: 'Convert', cls: 'cat-convert',
    workflows: [
      { id: 'C-01', name: 'Cart Recovery',         desc: '3-wave email + WhatsApp sequence recovers abandoned carts in 24h.' },
      { id: 'C-02', name: 'Inventory Drop Alert',  desc: 'Back-in-stock and low-stock alerts pushed via email and WhatsApp.' },
      { id: 'C-03', name: 'Dynamic Pricing',       desc: 'Adjusts prices based on demand signals and competitor data.' },
      { id: 'C-04', name: 'Gamified Checkout',     desc: 'Adds progress bars and milestone rewards to boost AOV at checkout.' },
    ],
  },
  {
    id: 'intel', label: 'Intelligence', cls: 'cat-intel',
    workflows: [
      { id: 'I-01', name: 'Trend Spotter',         desc: 'Monitors TikTok, Google Trends and social for viral product signals.' },
      { id: 'I-02', name: 'Competitor Radar',      desc: 'Weekly competitor pricing and content intelligence digest.' },
      { id: 'I-03', name: 'Customer Intel',        desc: 'Enriches customer profiles with psychographics and CLV predictions.' },
      { id: 'I-04', name: 'Review Analyser',       desc: 'NLP sentiment analysis on reviews → product improvement insights.' },
    ],
  },
  {
    id: 'retain', label: 'Retain', cls: 'cat-retain',
    workflows: [
      { id: 'R-01', name: 'CRM Follow-up',         desc: 'Post-purchase sequences: thank-you, how-to, upsell and review ask.' },
      { id: 'R-02', name: 'Loyalty Engine',        desc: 'Points, tiers, birthday rewards and VIP perks for repeat buyers.' },
      { id: 'R-03', name: 'Win-back Campaign',     desc: '3-stage re-engagement with escalating incentives for lapsed customers.' },
      { id: 'R-04', name: 'Churn Predictor',       desc: 'Flags at-risk customers 30 days before likely churn for intervention.' },
    ],
  },
  {
    id: 'support', label: 'Support', cls: 'cat-support',
    workflows: [
      { id: 'S-01', name: 'WhatsApp Support Bot',  desc: 'AI answers order, delivery and product queries via WhatsApp 24/7.' },
      { id: 'S-02', name: 'RAG Brain',             desc: 'GPT-4 answers product queries from your indexed knowledge base.' },
      { id: 'S-03', name: 'Review Responder',      desc: 'Auto-drafts personalised responses to Google and Trustpilot reviews.' },
      { id: 'S-04', name: 'CEO Assistant',         desc: 'Critical alerts escalated directly to CEO via WhatsApp with context.' },
    ],
  },
  {
    id: 'scale', label: 'Scale', cls: 'cat-scale',
    workflows: [
      { id: 'SC-01', name: 'UGC Harvester',        desc: 'Identifies top UGC creators and automates outreach + brief delivery.' },
      { id: 'SC-02', name: 'Amazon Expansion',     desc: 'Cross-lists Shopify products on Amazon with AI-optimised listings.' },
      { id: 'SC-03', name: 'Sales Automation',     desc: 'Detects buying signals and triggers personalised B2B outreach.' },
      { id: 'SC-04', name: 'SEO Meta Writer',      desc: 'Generates SEO-optimised product titles, descriptions and meta tags.' },
    ],
  },
];

// ── Mock data for demo mode ────────────────────────
const MOCK = {
  config: {
    brand_name: 'Luna Cosmetics',
    plan: 'scale',
    slug: 'luna-cosmetics',
    store_url: 'https://luna.myshopify.com',
    brand_voice: 'Warm, expert, inspiring',
    strategy_email: 'strategy@luna.com',
    ops_email: 'ops@luna.com',
  },
  workflows: CATEGORIES.flatMap((cat, ci) =>
    cat.workflows.map((wf, wi) => ({
      workflow_id: wf.id,
      is_active: Math.random() > 0.2,
      run_count: Math.floor(Math.random() * 4000) + 200,
      error_count: Math.floor(Math.random() * 8),
      last_run_at: new Date(Date.now() - Math.random() * 3600000).toISOString(),
    }))
  ),
  analytics: {
    leads: Array.from({ length: 120 }, (_, i) => ({
      score: Math.floor(Math.random() * 100),
      category: ['hot','warm','cold'][Math.floor(Math.random()*3)],
      created_at: new Date(Date.now() - Math.random() * 30 * 86400000).toISOString(),
    })),
    carts: Array.from({ length: 80 }, () => ({
      status: Math.random() > 0.4 ? 'recovered' : 'abandoned',
      cart_value: +(Math.random() * 180 + 20).toFixed(2),
      recovery_value: +(Math.random() * 150 + 15).toFixed(2),
      created_at: new Date(Date.now() - Math.random() * 30 * 86400000).toISOString(),
    })),
    loyalty: Array.from({ length: 300 }, () => ({
      points: Math.floor(Math.random() * 500) + 50,
      event_type: ['purchase','referral','review'][Math.floor(Math.random()*3)],
    })),
    tickets: Array.from({ length: 45 }, () => ({
      status: Math.random() > 0.3 ? 'closed' : 'open',
    })),
    winback: [],
    workflows: [],
  },
  attribution: [
    { workflow_id: 'C-01', total: 18240, count: 47 },
    { workflow_id: 'R-02', total: 12680, count: 83 },
    { workflow_id: 'A-01', total: 9450, count: 31 },
    { workflow_id: 'R-01', total: 7120, count: 62 },
    { workflow_id: 'SC-03', total: 5870, count: 19 },
    { workflow_id: 'C-02', total: 3210, count: 28 },
  ],
  emailStats: {
    summary: { sent: 4820, delivered: 4750, opened: 1995, clicked: 618, replied: 89, open_rate: 42.0, click_rate: 13.0, reply_rate: 1.9 },
    by_workflow: [
      { workflow_id: 'C-01', sent: 1240, opened: 558, clicked: 186, open_rate: 45.0 },
      { workflow_id: 'R-01', sent: 980,  opened: 421, clicked: 98,  open_rate: 43.0 },
      { workflow_id: 'A-02', sent: 640,  opened: 224, clicked: 64,  open_rate: 35.0 },
    ],
  },
  cohorts: [
    { cohort: '2025-10', size: 143, retention: [68, 41, 29, 22, 18] },
    { cohort: '2025-11', size: 167, retention: [72, 44, 31, 24] },
    { cohort: '2025-12', size: 198, retention: [69, 40, 27] },
    { cohort: '2026-01', size: 221, retention: [75, 46] },
    { cohort: '2026-02', size: 189, retention: [71] },
    { cohort: '2026-03', size: 234, retention: [] },
  ],
  logs: Array.from({ length: 30 }, (_, i) => {
    const wfIds = ['A-01','C-01','R-01','R-02','S-01','SC-04','I-03','A-02','C-02'];
    const wf = wfIds[i % wfIds.length];
    const ok = Math.random() > 0.08;
    return {
      id: `log-${i}`,
      workflow_id: wf,
      status: ok ? 'completed' : 'failed',
      duration_ms: Math.floor(Math.random() * 4000) + 200,
      input_summary: `Demo input for ${wf}`,
      output_summary: ok ? `Processed successfully` : null,
      error_message: ok ? null : 'OpenAI timeout',
      executed_at: new Date(Date.now() - i * 4 * 60000).toISOString(),
    };
  }),
  content: [
    { id: '1', title: 'Spring Skincare Guide 2026', type: 'blog', platform: 'Website', status: 'published', keyword: 'spring skincare', published_at: '2026-03-01T10:00:00Z' },
    { id: '2', title: '5 Reasons to Switch to Natural Serums', type: 'email', platform: 'Brevo', status: 'scheduled', keyword: 'natural serum', scheduled_at: '2026-04-05T09:00:00Z' },
    { id: '3', title: 'Vitamin C Routine — TikTok Script', type: 'social', platform: 'TikTok', status: 'draft', keyword: 'vitamin c routine' },
    { id: '4', title: 'New Retinol Launch Campaign', type: 'email', platform: 'Brevo', status: 'draft', keyword: 'retinol launch' },
    { id: '5', title: 'Customer Love Story — Emma', type: 'ugc', platform: 'Instagram', status: 'published', published_at: '2026-03-15T14:00:00Z' },
  ],
  abTests: [
    { id: '1', workflow_id: 'C-01', name: 'Cart Recovery Subject Lines', status: 'running', variant_a: 'You left something behind 🛒', variant_b: 'Your cart misses you — 10% off inside', a_sent: 480, a_opened: 211, b_sent: 480, b_opened: 254, winner: null },
    { id: '2', workflow_id: 'A-02', name: 'Cold Outreach CTA Copy', status: 'completed', variant_a: 'Book a 15-min call', variant_b: 'See how it works →', a_sent: 320, a_opened: 108, b_sent: 320, b_opened: 144, winner: 'B' },
    { id: '3', workflow_id: 'R-01', name: 'Post-purchase Timing', status: 'running', variant_a: 'Send at 1h after order', variant_b: 'Send at 24h after order', a_sent: 290, a_opened: 148, b_sent: 290, b_opened: 127, winner: null },
  ],
  ragDocs: [
    { id: '1', name: 'Product Handbook 2026.pdf', size_bytes: 2400000, status: 'indexed', chunk_count: 680, uploaded_at: '2026-02-10T12:00:00Z' },
    { id: '2', name: 'FAQ — Shipping & Returns.docx', size_bytes: 480000, status: 'indexed', chunk_count: 137, uploaded_at: '2026-02-28T09:30:00Z' },
    { id: '3', name: 'Ingredient Glossary.pdf', size_bytes: 1100000, status: 'indexed', chunk_count: 314, uploaded_at: '2026-03-12T14:00:00Z' },
  ],
  integrations: [
    { key: 'openai',    label: 'OpenAI',          connected: true,  env_var: 'OPENAI_API_KEY',        workflows: ['All 24 workflows'] },
    { key: 'supabase',  label: 'Supabase',         connected: true,  env_var: 'SUPABASE_URL',          workflows: ['All 24 workflows'] },
    { key: 'shopify',   label: 'Shopify',          connected: true,  env_var: 'SHOPIFY_ACCESS_TOKEN',  workflows: ['C-01','C-02','C-04','R-01','SC-04'] },
    { key: 'brevo',     label: 'Brevo (Email)',    connected: true,  env_var: 'BREVO_API_KEY',         workflows: ['A-02','C-01','R-01','R-02'] },
    { key: 'slack',     label: 'Slack',            connected: true,  env_var: 'SLACK_BOT_TOKEN',       workflows: ['All 24 workflows'] },
    { key: 'whatsapp',  label: 'WhatsApp',         connected: false, env_var: 'WHATSAPP_ACCESS_TOKEN', workflows: ['A-03','S-01','S-04'] },
    { key: 'instagram', label: 'Instagram',        connected: false, env_var: 'INSTAGRAM_ACCESS_TOKEN',workflows: ['A-03','SC-01'] },
    { key: 'pinecone',  label: 'Pinecone (RAG)',   connected: true,  env_var: 'PINECONE_API_KEY',      workflows: ['S-02'] },
    { key: 'google',    label: 'Google Ads',       connected: false, env_var: 'GOOGLE_SERVICE_ACCOUNT',workflows: ['I-02','I-04'] },
  ],
};

// ── API helper ────────────────────────────────────
async function api(method, path, body) {
  if (state.demo) return mockApi(method, path, body);
  const opts = {
    method,
    headers: { 'x-api-key': state.key, 'Content-Type': 'application/json' },
  };
  if (body) opts.body = JSON.stringify(body);
  const r = await fetch(path, opts);
  if (!r.ok) {
    const err = await r.json().catch(() => ({ error: r.statusText }));
    throw new Error(err.error || r.statusText);
  }
  return r.json();
}

function mockApi(method, path, body) {
  return new Promise(resolve => setTimeout(() => {
    if (path.includes('/config/'))          return resolve(MOCK.config);
    if (path.includes('/workflows') && method === 'GET') return resolve(MOCK.workflows);
    if (path.includes('/analytics'))        return resolve(MOCK.analytics);
    if (path.includes('/attribution'))      return resolve(MOCK.attribution);
    if (path.includes('/email-stats'))      return resolve(MOCK.emailStats);
    if (path.includes('/cohorts'))          return resolve(MOCK.cohorts);
    if (path.includes('/logs'))             return resolve(MOCK.logs);
    if (path.includes('/content'))         return resolve(MOCK.content);
    if (path.includes('/ab-tests'))        return resolve(MOCK.abTests);
    if (path.includes('/rag-docs'))        return resolve(MOCK.ragDocs);
    if (path.includes('/integrations'))    return resolve(MOCK.integrations);
    if (method === 'PATCH' || method === 'PUT') return resolve({ ...(body || {}), updated: true });
    if (method === 'POST')  return resolve({ id: 'demo-' + Date.now(), ...(body || {}), created: true });
    if (method === 'DELETE') return resolve({ deleted: true });
    resolve({});
  }, 180));
}

// ── Toast ─────────────────────────────────────────
function toast(msg, type = 'info') {
  const el = document.createElement('div');
  el.className = `toast ${type}`;
  el.textContent = msg;
  document.getElementById('toast-container').appendChild(el);
  setTimeout(() => el.remove(), 3500);
}

// ── Modal ─────────────────────────────────────────
function openModal(title, bodyHtml, footerHtml = '') {
  document.getElementById('modal-title').textContent = title;
  document.getElementById('modal-body').innerHTML = bodyHtml;
  const modal = document.getElementById('modal');
  // Remove old footer if any
  const oldFtr = modal.querySelector('.modal-footer');
  if (oldFtr) oldFtr.remove();
  if (footerHtml) {
    const ftr = document.createElement('div');
    ftr.className = 'modal-footer';
    ftr.innerHTML = footerHtml;
    modal.querySelector('.modal-box').appendChild(ftr);
  }
  modal.style.display = 'flex';
}
function closeModal() { document.getElementById('modal').style.display = 'none'; }

// ── Screen switching ──────────────────────────────
function showScreen(id) {
  document.querySelectorAll('.screen').forEach(s => s.classList.remove('active'));
  document.getElementById(id).classList.add('active');
}

// ── Connect ───────────────────────────────────────
async function connect(slug, key) {
  state.slug = slug;
  state.key  = key;
  const config = await api('GET', `/api/config/${slug}`);
  state.config = config;
  enterApp();
}

function connectDemo() {
  state.demo   = true;
  state.slug   = 'luna-cosmetics';
  state.config = MOCK.config;
  enterApp();
}

function enterApp() {
  // Sidebar tenant info
  const cfg = state.config;
  const planCls = { growth: 'pill-growth', scale: 'pill-scale', enterprise: 'pill-enterprise' }[cfg.plan] || 'pill-info';
  document.getElementById('sidebar-tenant').innerHTML = `
    <strong>${cfg.brand_name || cfg.slug}</strong>
    <span class="pill ${planCls}">${(cfg.plan || 'growth').toUpperCase()}</span>
  `;
  if (state.demo) {
    document.getElementById('demo-mode-badge').style.display = 'block';
  }
  showScreen('screen-app');
  navTo('overview');
  if (state.demo) startDemoFeed();
  else connectSSE();
}

function signOut() {
  if (state.sseSource) { state.sseSource.close(); state.sseSource = null; }
  if (state.demoFeedTimer) { clearInterval(state.demoFeedTimer); state.demoFeedTimer = null; }
  state.slug = null; state.key = null; state.demo = false; state.config = null; state.cache = {};
  state.feedItems = [];
  showScreen('screen-connect');
}

// ── Navigation ────────────────────────────────────
const VIEW_RENDERERS = {
  overview:     viewOverview,
  'live-feed':  viewLiveFeed,
  workflows:    viewWorkflows,
  analytics:    viewAnalytics,
  logs:         viewLogs,
  content:      viewContent,
  'ab-tests':   viewAbTests,
  knowledge:    viewKnowledge,
  integrations: viewIntegrations,
  settings:     viewSettings,
};

function navTo(view) {
  document.querySelectorAll('.nav-item').forEach(el => el.classList.toggle('active', el.dataset.view === view));
  const main = document.getElementById('main-content');
  main.innerHTML = '<div class="skeleton skel-h40 skel-mb8"></div><div class="skeleton skel-h80 skel-mb8"></div><div class="skeleton skel-h80"></div>';
  const fn = VIEW_RENDERERS[view];
  if (fn) fn(main);
}

// ═══════════════════════════════════════════════════
// VIEW: OVERVIEW
// ═══════════════════════════════════════════════════
async function viewOverview(el) {
  const [wfsData, analyticsData] = await Promise.all([
    api('GET', `/api/tenants/${state.slug}/workflows`),
    api('GET', `/api/tenants/${state.slug}/analytics`),
  ]);

  const activeWfs   = wfsData.filter(w => w.is_active).length;
  const leads       = analyticsData.leads || [];
  const carts       = analyticsData.carts || [];
  const loyalty     = analyticsData.loyalty || [];
  const tickets     = analyticsData.tickets || [];

  const hotLeads    = leads.filter(l => l.category === 'hot').length;
  const recovered   = carts.filter(c => c.status === 'recovered').length;
  const recovVal    = carts.filter(c => c.status === 'recovered').reduce((s, c) => s + (c.recovery_value || 0), 0);
  const loyPts      = loyalty.reduce((s, l) => s + (l.points || 0), 0);
  const closedTx    = tickets.filter(t => t.status === 'closed').length;

  const wfRows = wfsData.slice(0, 8).map(w => {
    const meta = CATEGORIES.flatMap(c => c.workflows).find(m => m.id === w.workflow_id);
    return `<tr>
      <td><span class="fw-600">${w.workflow_id}</span></td>
      <td class="truncate" style="max-width:160px">${meta?.name || w.workflow_id}</td>
      <td><span class="status-badge ${w.is_active ? 'completed' : ''}">${w.is_active ? 'Active' : 'Off'}</span></td>
      <td>${(w.run_count || 0).toLocaleString()}</td>
      <td style="color:${(w.error_count||0)>0?'var(--red)':'var(--text-3)'}">${w.error_count || 0}</td>
    </tr>`;
  }).join('');

  el.innerHTML = `
    <div class="view-header">
      <div><div class="view-title">Overview</div><div class="view-sub">Real-time summary for ${state.config?.brand_name || state.slug}</div></div>
      <button class="btn btn-ghost btn-sm" onclick="navTo('analytics')">Full analytics →</button>
    </div>

    <div class="stats-grid">
      <div class="stat-card">
        <div class="stat-value">${activeWfs}<span style="font-size:1rem;color:var(--text-3)">/24</span></div>
        <div class="stat-label">Active workflows</div>
      </div>
      <div class="stat-card green">
        <div class="stat-value">${hotLeads}</div>
        <div class="stat-label">Hot leads this month</div>
        <div class="stat-delta up">↑ ${leads.length} total captured</div>
      </div>
      <div class="stat-card">
        <div class="stat-value">£${recovVal.toLocaleString('en-GB',{maximumFractionDigits:0})}</div>
        <div class="stat-label">Cart revenue recovered</div>
        <div class="stat-delta up">↑ ${recovered} carts rescued</div>
      </div>
      <div class="stat-card violet">
        <div class="stat-value">${loyPts.toLocaleString()}</div>
        <div class="stat-label">Loyalty points issued</div>
      </div>
      <div class="stat-card amber">
        <div class="stat-value">${closedTx}</div>
        <div class="stat-label">Support tickets resolved</div>
      </div>
      <div class="stat-card green">
        <div class="stat-value">${wfsData.reduce((s,w)=>s+(w.run_count||0),0).toLocaleString()}</div>
        <div class="stat-label">Total workflow runs</div>
      </div>
      <div class="stat-card pink">
        <div class="stat-value">${wfsData.reduce((s,w)=>s+(w.error_count||0),0)}</div>
        <div class="stat-label">Total errors</div>
      </div>
      <div class="stat-card emerald">
        <div class="stat-value">${carts.length > 0 ? Math.round(recovered/carts.length*100) : 0}%</div>
        <div class="stat-label">Cart recovery rate</div>
      </div>
    </div>

    <div class="card">
      <div class="card-header">
        <span class="card-title">Workflow status</span>
        <button class="btn btn-ghost btn-sm" onclick="navTo('workflows')">Manage all →</button>
      </div>
      <table class="log-table">
        <thead><tr><th>ID</th><th>Name</th><th>Status</th><th>Runs</th><th>Errors</th></tr></thead>
        <tbody>${wfRows || '<tr><td colspan="5" class="text-muted" style="text-align:center;padding:20px">No workflows configured yet</td></tr>'}</tbody>
      </table>
    </div>
  `;
}

// ═══════════════════════════════════════════════════
// VIEW: LIVE FEED (SSE)
// ═══════════════════════════════════════════════════
function viewLiveFeed(el) {
  el.innerHTML = `
    <div class="view-header">
      <div><div class="view-title">Live Feed</div><div class="view-sub">Real-time workflow events as they happen</div></div>
      <span id="feed-status" class="pill pill-active">● Live</span>
    </div>
    <div id="feed-list" class="feed-list">
      ${state.feedItems.length === 0 ? `<div class="empty-state"><div class="empty-state-icon">📡</div><h3>Waiting for events</h3><p>Workflow runs will appear here in real time</p></div>` : ''}
    </div>
  `;
  renderFeedItems();
}

function renderFeedItems() {
  const list = document.getElementById('feed-list');
  if (!list) return;
  if (state.feedItems.length === 0) return;
  list.innerHTML = state.feedItems.slice(0, 60).map(item => `
    <div class="feed-item">
      <div class="feed-dot ${item.type || 'success'}"></div>
      <div class="feed-body">
        <div class="feed-title">${item.title}</div>
        <div class="feed-meta">${item.meta || ''}</div>
      </div>
      <div class="feed-time">${item.timeStr}</div>
    </div>
  `).join('');
}

function pushFeedItem(item) {
  state.feedItems.unshift(item);
  if (state.feedItems.length > 100) state.feedItems.pop();
  document.getElementById('nav-feed-dot') && (document.getElementById('nav-feed-dot').style.display = 'inline-block');
  renderFeedItems();
}

function connectSSE() {
  if (state.sseSource) state.sseSource.close();
  const url = `/api/tenants/${state.slug}/events?x-api-key=${encodeURIComponent(state.key)}`;
  const es = new EventSource(url);
  state.sseSource = es;
  es.onmessage = (e) => {
    try {
      const ev = JSON.parse(e.data);
      pushFeedItem({
        type:    ev.status === 'completed' ? 'success' : ev.status === 'running' ? 'running' : ev.type === 'cascade' ? 'cascade' : 'success',
        title:   ev.type === 'cascade' ? `Cascade: ${ev.triggered} triggered by ${ev.source}` : `${ev.workflow_id} — ${ev.status}`,
        meta:    ev.duration ? `${ev.duration}ms` : '',
        timeStr: new Date().toLocaleTimeString(),
      });
    } catch (_) {}
  };
  es.onerror = () => { document.getElementById('feed-status') && (document.getElementById('feed-status').className = 'pill pill-amber'); };
}

function startDemoFeed() {
  const DEMO_EVENTS = [
    { type: 'success', title: 'A-01 Smart Lead Capture — completed', meta: 'Score: 87 (hot) → Slack #hot-leads + Calendly', timeStr: '' },
    { type: 'running', title: 'C-01 Cart Recovery — running', meta: 'Wave 1 email queued for 3 carts', timeStr: '' },
    { type: 'success', title: 'R-02 Loyalty Engine — completed', meta: '450 points issued to emma@test.com', timeStr: '' },
    { type: 'cascade', title: 'Cascade: R-01 triggered by A-01', meta: 'Post-purchase follow-up sequence started', timeStr: '' },
    { type: 'success', title: 'SC-04 SEO Meta Writer — completed', meta: '3 product pages optimised', timeStr: '' },
    { type: 'success', title: 'I-03 Customer Intel — completed', meta: 'CLV prediction updated for 12 customers', timeStr: '' },
    { type: 'running', title: 'S-01 WhatsApp Support — running', meta: 'Query: "Where is my order #4821"', timeStr: '' },
    { type: 'success', title: 'S-01 WhatsApp Support — completed', meta: 'Replied in 1.2s — tracking link sent', timeStr: '' },
    { type: 'success', title: 'A-03 Instagram DM Bot — completed', meta: '2 new leads captured from story replies', timeStr: '' },
    { type: 'cascade', title: 'Cascade: C-01 triggered by C-04', meta: 'Cart recovery wave 2 triggered', timeStr: '' },
  ];
  let idx = 0;
  const tick = () => {
    const ev = { ...DEMO_EVENTS[idx % DEMO_EVENTS.length], timeStr: new Date().toLocaleTimeString() };
    pushFeedItem(ev);
    idx++;
  };
  tick();
  state.demoFeedTimer = setInterval(tick, 4000);
}

// ═══════════════════════════════════════════════════
// VIEW: WORKFLOWS
// ═══════════════════════════════════════════════════
async function viewWorkflows(el) {
  const wfsData = await api('GET', `/api/tenants/${state.slug}/workflows`);
  const wfMap   = {};
  wfsData.forEach(w => { wfMap[w.workflow_id] = w; });

  const catFilter = el._catFilter || 'all';

  function renderCards() {
    const cats = catFilter === 'all' ? CATEGORIES : CATEGORIES.filter(c => c.id === catFilter);
    return cats.map(cat => `
      <div class="section-heading">${cat.label}</div>
      <div class="wf-grid">
        ${cat.workflows.map(wf => {
          const state_wf = wfMap[wf.id] || { is_active: false, run_count: 0, error_count: 0 };
          const isActive = state_wf.is_active;
          return `
            <div class="wf-card" id="wf-card-${wf.id}">
              <div class="wf-card-header">
                <div class="wf-icon ${cat.cls}">${wf.id}</div>
                <div class="wf-info">
                  <div class="wf-id">${cat.label}</div>
                  <div class="wf-name">${wf.name}</div>
                </div>
              </div>
              <div class="wf-desc">${wf.desc}</div>
              <div class="wf-footer">
                <div class="wf-stats">
                  <span>${(state_wf.run_count || 0).toLocaleString()} runs</span>
                  <span style="color:${(state_wf.error_count||0)>0?'var(--red)':'var(--text-3)'}">${state_wf.error_count || 0} errors</span>
                </div>
                <div class="wf-actions">
                  <button class="btn btn-ghost btn-xs" onclick="triggerModal('${wf.id}')">▶ Run</button>
                  <label class="toggle">
                    <input type="checkbox" ${isActive ? 'checked' : ''} onchange="toggleWorkflow('${wf.id}', this.checked)"/>
                    <div class="toggle-track"></div>
                    <div class="toggle-thumb"></div>
                  </label>
                </div>
              </div>
            </div>
          `;
        }).join('')}
      </div>
    `).join('');
  }

  el.innerHTML = `
    <div class="view-header">
      <div><div class="view-title">Workflows</div><div class="view-sub">24 AI automations — toggle on/off or trigger manually</div></div>
    </div>
    <div style="display:flex;gap:8px;margin-bottom:20px;flex-wrap:wrap">
      <button class="btn btn-sm ${catFilter==='all'?'btn-primary':'btn-ghost'}" onclick="filterWorkflows('all')">All</button>
      ${CATEGORIES.map(c => `<button class="btn btn-sm ${catFilter===c.id?'btn-primary':'btn-ghost'}" onclick="filterWorkflows('${c.id}')">${c.label}</button>`).join('')}
    </div>
    <div id="wf-cards-wrap">${renderCards()}</div>
  `;
  el._catFilter = catFilter;
}

window.filterWorkflows = function(cat) {
  const el = document.getElementById('main-content');
  el._catFilter = cat;
  viewWorkflows(el);
};

window.toggleWorkflow = async function(wfId, active) {
  try {
    await api('PATCH', `/api/tenants/${state.slug}/workflows/${wfId}`, { is_active: active });
    toast(`${wfId} ${active ? 'activated' : 'deactivated'}`, 'success');
  } catch (e) { toast(e.message, 'error'); }
};

window.triggerModal = async function(wfId) {
  const meta = CATEGORIES.flatMap(c => c.workflows).find(m => m.id === wfId);
  let payload = {};
  if (!state.demo) {
    try { payload = await api('GET', `/api/tenants/${state.slug}/workflows/${wfId}/default-payload`); } catch (_) {}
  }
  openModal(`Trigger ${wfId}: ${meta?.name || wfId}`,
    `<p class="text-sm text-muted mb-16">Edit the payload then click Run. In demo mode this is simulated.</p>
     <div class="form-group"><label>Payload (JSON)</label><textarea id="trigger-payload" rows="6">${JSON.stringify(payload, null, 2)}</textarea></div>`,
    `<button class="btn btn-ghost" onclick="closeModal()">Cancel</button>
     <button class="btn btn-primary" onclick="doTrigger('${wfId}')">▶ Run workflow</button>`
  );
};

window.doTrigger = async function(wfId) {
  let payload = {};
  try { payload = JSON.parse(document.getElementById('trigger-payload').value); } catch (_) {}
  closeModal();
  try {
    await api('POST', `/api/tenants/${state.slug}/workflows/${wfId}/trigger`, { payload });
    toast(`${wfId} triggered successfully`, 'success');
  } catch (e) { toast(e.message, 'error'); }
};

// ═══════════════════════════════════════════════════
// VIEW: ANALYTICS
// ═══════════════════════════════════════════════════
async function viewAnalytics(el) {
  el.innerHTML = `
    <div class="view-header"><div class="view-title">Analytics</div></div>
    <div class="tab-bar">
      <button class="tab-btn active" onclick="switchTab('tab-overview', this)">Overview</button>
      <button class="tab-btn" onclick="switchTab('tab-revenue', this)">Revenue Attribution</button>
      <button class="tab-btn" onclick="switchTab('tab-cohort', this)">Cohort Retention</button>
      <button class="tab-btn" onclick="switchTab('tab-email', this)">Email Performance</button>
    </div>
    <div id="tab-overview" class="tab-pane active"><div class="skeleton skel-h80 skel-mb8"></div><div class="skeleton skel-h80"></div></div>
    <div id="tab-revenue"  class="tab-pane"></div>
    <div id="tab-cohort"   class="tab-pane"></div>
    <div id="tab-email"    class="tab-pane"></div>
  `;
  loadAnalyticsTab('tab-overview');
}

window.switchTab = function(tabId, btn) {
  document.querySelectorAll('.tab-btn').forEach(b => b.classList.remove('active'));
  document.querySelectorAll('.tab-pane').forEach(p => p.classList.remove('active'));
  btn.classList.add('active');
  document.getElementById(tabId).classList.add('active');
  loadAnalyticsTab(tabId);
};

async function loadAnalyticsTab(tabId) {
  const pane = document.getElementById(tabId);
  if (!pane || pane.dataset.loaded) return;
  pane.dataset.loaded = '1';

  if (tabId === 'tab-overview') {
    const data = await api('GET', `/api/tenants/${state.slug}/analytics`);
    const leads  = data.leads  || [];
    const carts  = data.carts  || [];
    const loyalty= data.loyalty|| [];
    const tickets= data.tickets|| [];
    const byDay = {};
    leads.forEach(l => {
      const d = l.created_at?.slice(0,10) || 'unknown';
      byDay[d] = (byDay[d] || 0) + 1;
    });
    const days = Object.keys(byDay).sort().slice(-14);
    const maxLeads = Math.max(...days.map(d => byDay[d]), 1);
    pane.innerHTML = `
      <div class="stats-grid" style="grid-template-columns:repeat(3,1fr)">
        <div class="stat-card"><div class="stat-value">${leads.length}</div><div class="stat-label">Total leads</div></div>
        <div class="stat-card green"><div class="stat-value">${leads.filter(l=>l.category==='hot').length}</div><div class="stat-label">Hot leads</div></div>
        <div class="stat-card"><div class="stat-value">${leads.filter(l=>l.category==='warm').length}</div><div class="stat-label">Warm leads</div></div>
        <div class="stat-card"><div class="stat-value">${carts.filter(c=>c.status==='recovered').length}</div><div class="stat-label">Carts recovered</div></div>
        <div class="stat-card amber"><div class="stat-value">£${carts.filter(c=>c.status==='recovered').reduce((s,c)=>s+(c.recovery_value||0),0).toLocaleString('en-GB',{maximumFractionDigits:0})}</div><div class="stat-label">Recovery revenue</div></div>
        <div class="stat-card violet"><div class="stat-value">${loyalty.reduce((s,l)=>s+(l.points||0),0).toLocaleString()}</div><div class="stat-label">Loyalty points</div></div>
      </div>
      <div class="card">
        <div class="card-header"><span class="card-title">Lead volume — last 14 days</span></div>
        <div style="display:flex;align-items:flex-end;gap:4px;height:80px;padding-top:8px">
          ${days.map(d => `
            <div style="flex:1;display:flex;flex-direction:column;align-items:center;gap:4px">
              <div style="width:100%;background:var(--accent);opacity:.8;border-radius:3px 3px 0 0;height:${Math.round((byDay[d]/maxLeads)*64)}px"></div>
              <span style="font-size:.6rem;color:var(--text-3);transform:rotate(-45deg);transform-origin:top right;white-space:nowrap">${d.slice(5)}</span>
            </div>
          `).join('')}
        </div>
      </div>
    `;
  }

  if (tabId === 'tab-revenue') {
    const data = await api('GET', `/api/tenants/${state.slug}/revenue-attribution`);
    const maxVal = Math.max(...data.map(d => d.total), 1);
    pane.innerHTML = `
      <div class="card">
        <div class="card-header"><span class="card-title">Revenue by workflow (last 30 days)</span></div>
        <div class="attr-list">
          ${data.length === 0
            ? '<div class="empty-state"><div class="empty-state-icon">💰</div><h3>No attribution data yet</h3><p>Revenue attribution appears when workflows generate sales</p></div>'
            : data.map(r => `
                <div class="attr-row">
                  <div class="attr-label">${r.workflow_id}</div>
                  <div class="attr-bar-wrap"><div class="attr-bar" style="width:${Math.round((r.total/maxVal)*100)}%"></div></div>
                  <div class="attr-val">£${r.total.toLocaleString('en-GB',{maximumFractionDigits:0})}</div>
                </div>
              `).join('')
          }
        </div>
      </div>
    `;
  }

  if (tabId === 'tab-cohort') {
    const data = await api('GET', `/api/tenants/${state.slug}/cohorts`);
    if (!data.length) {
      pane.innerHTML = '<div class="empty-state"><div class="empty-state-icon">📊</div><h3>No cohort data yet</h3><p>Cohort data builds up after customer repeat purchases</p></div>';
      return;
    }
    const maxMonths = Math.max(...data.map(c => c.retention.length));
    const headers = ['Cohort','Size',...Array.from({length:maxMonths},(_,i)=>`M+${i+1}`)];
    pane.innerHTML = `
      <div class="card">
        <div class="card-header"><span class="card-title">Cohort retention heatmap</span><span class="text-xs text-muted">% of cohort still purchasing</span></div>
        <div class="cohort-table">
          <table>
            <thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead>
            <tbody>
              ${data.map(c => `
                <tr>
                  <td class="cohort-label">${c.cohort}</td>
                  <td>${c.size}</td>
                  ${c.retention.map(pct => `
                    <td class="cohort-cell" style="background:rgba(56,189,248,${(pct/100)*0.8});color:${pct>50?'#0f172a':'var(--text-1)'}">${pct}%</td>
                  `).join('')}
                  ${Array.from({length: maxMonths - c.retention.length}, () => '<td></td>').join('')}
                </tr>
              `).join('')}
            </tbody>
          </table>
        </div>
      </div>
    `;
  }

  if (tabId === 'tab-email') {
    const data = await api('GET', `/api/tenants/${state.slug}/email-stats`);
    const s = data.summary || {};
    pane.innerHTML = `
      <div class="email-stats-row">
        <div class="stat-card"><div class="stat-value">${(s.sent||0).toLocaleString()}</div><div class="stat-label">Emails delivered</div></div>
        <div class="stat-card green"><div class="stat-value">${s.open_rate||0}%</div><div class="stat-label">Open rate</div></div>
        <div class="stat-card"><div class="stat-value">${s.click_rate||0}%</div><div class="stat-label">Click rate</div></div>
        <div class="stat-card amber"><div class="stat-value">${s.reply_rate||0}%</div><div class="stat-label">Reply rate</div></div>
      </div>
      <div class="card">
        <div class="card-header"><span class="card-title">Performance by workflow</span></div>
        <table class="log-table">
          <thead><tr><th>Workflow</th><th>Sent</th><th>Opened</th><th>Clicked</th><th>Open rate</th></tr></thead>
          <tbody>
            ${(data.by_workflow||[]).map(w => `
              <tr>
                <td>${w.workflow_id}</td>
                <td>${w.sent.toLocaleString()}</td>
                <td>${w.opened.toLocaleString()}</td>
                <td>${(w.clicked||0).toLocaleString()}</td>
                <td><span class="pill ${w.open_rate>40?'pill-active':'pill-info'}">${w.open_rate}%</span></td>
              </tr>
            `).join('') || '<tr><td colspan="5" class="text-muted" style="text-align:center;padding:20px">No email events yet</td></tr>'}
          </tbody>
        </table>
      </div>
    `;
  }
}

// ═══════════════════════════════════════════════════
// VIEW: LOGS
// ═══════════════════════════════════════════════════
async function viewLogs(el) {
  const logs = await api('GET', `/api/tenants/${state.slug}/logs?limit=50`);
  el.innerHTML = `
    <div class="view-header">
      <div><div class="view-title">Execution Logs</div><div class="view-sub">Last 50 workflow runs</div></div>
    </div>
    <div class="card" style="padding:0;overflow:hidden">
      <table class="log-table">
        <thead><tr><th>Time</th><th>Workflow</th><th>Status</th><th>Duration</th><th>Input</th><th>Output / Error</th></tr></thead>
        <tbody>
          ${logs.length === 0
            ? '<tr><td colspan="6" class="text-muted" style="text-align:center;padding:28px">No logs yet</td></tr>'
            : logs.map(l => `
                <tr>
                  <td class="log-duration">${new Date(l.executed_at).toLocaleTimeString()}</td>
                  <td><span class="fw-600">${l.workflow_id}</span></td>
                  <td><span class="status-badge ${l.status}">${l.status}</span></td>
                  <td class="log-duration">${l.duration_ms ? l.duration_ms + 'ms' : '—'}</td>
                  <td class="log-input">${l.input_summary || '—'}</td>
                  <td class="log-output" style="color:${l.status==='failed'?'var(--red)':''}">
                    ${l.status === 'failed' ? l.error_message || 'Error' : l.output_summary || '—'}
                  </td>
                </tr>
              `).join('')}
        </tbody>
      </table>
    </div>
  `;
}

// ═══════════════════════════════════════════════════
// VIEW: CONTENT CALENDAR
// ═══════════════════════════════════════════════════
async function viewContent(el) {
  const items = await api('GET', `/api/tenants/${state.slug}/content`);
  const byStatus = { draft: [], scheduled: [], published: [] };
  items.forEach(i => { (byStatus[i.status] || byStatus.draft).push(i); });

  const platformTag = (p) => `<span class="tag">${p}</span>`;
  const typeTag = (t) => `<span class="tag">${t}</span>`;

  el.innerHTML = `
    <div class="view-header">
      <div><div class="view-title">Content Calendar</div><div class="view-sub">AI-generated content pipeline</div></div>
      <button class="btn btn-primary btn-sm" onclick="openNewContentModal()">+ New item</button>
    </div>
    <div class="kanban">
      ${['draft','scheduled','published'].map(status => `
        <div class="kanban-col">
          <div class="kanban-col-header">
            <span>${status.charAt(0).toUpperCase()+status.slice(1)}</span>
            <span>${byStatus[status].length}</span>
          </div>
          <div class="kanban-items">
            ${byStatus[status].map(item => `
              <div class="kanban-card">
                <div class="kanban-card-title">${item.title}</div>
                <div class="kanban-card-meta">${item.keyword ? '🔑 ' + item.keyword : ''}</div>
                <div class="kanban-card-tags">
                  ${platformTag(item.platform)}
                  ${typeTag(item.type)}
                  ${item.scheduled_at ? `<span class="tag">📅 ${new Date(item.scheduled_at).toLocaleDateString()}</span>` : ''}
                </div>
              </div>
            `).join('') || '<div class="text-muted text-sm" style="padding:8px 0">Nothing here</div>'}
          </div>
        </div>
      `).join('')}
    </div>
  `;
}

window.openNewContentModal = function() {
  openModal('New content item',
    `<div class="form-group"><label>Title *</label><input id="ct-title" type="text" placeholder="Spring Skincare Guide 2026"/></div>
     <div class="form-grid-2">
       <div class="form-group"><label>Type</label><select id="ct-type"><option>blog</option><option>email</option><option>social</option><option>ugc</option></select></div>
       <div class="form-group"><label>Platform</label><select id="ct-platform"><option>Website</option><option>Brevo</option><option>Instagram</option><option>TikTok</option><option>LinkedIn</option></select></div>
       <div class="form-group"><label>Keyword</label><input id="ct-keyword" type="text" placeholder="spring skincare"/></div>
       <div class="form-group"><label>Schedule date</label><input id="ct-sched" type="datetime-local"/></div>
     </div>`,
    `<button class="btn btn-ghost" onclick="closeModal()">Cancel</button>
     <button class="btn btn-primary" onclick="doCreateContent()">Create</button>`
  );
};

window.doCreateContent = async function() {
  const title = document.getElementById('ct-title').value.trim();
  if (!title) { toast('Title is required', 'error'); return; }
  const body = {
    title,
    type:         document.getElementById('ct-type').value,
    platform:     document.getElementById('ct-platform').value,
    keyword:      document.getElementById('ct-keyword').value,
    scheduled_at: document.getElementById('ct-sched').value || null,
    status: 'draft',
  };
  try {
    await api('POST', `/api/tenants/${state.slug}/content`, body);
    closeModal();
    toast('Content item created', 'success');
    navTo('content');
  } catch (e) { toast(e.message, 'error'); }
};

// ═══════════════════════════════════════════════════
// VIEW: A/B TESTS
// ═══════════════════════════════════════════════════
async function viewAbTests(el) {
  const tests = await api('GET', `/api/tenants/${state.slug}/ab-tests`);

  el.innerHTML = `
    <div class="view-header">
      <div><div class="view-title">A/B Tests</div><div class="view-sub">Optimise your workflow messaging with data</div></div>
      <button class="btn btn-primary btn-sm" onclick="openNewAbModal()">+ New test</button>
    </div>
    <div class="ab-grid">
      ${tests.length === 0
        ? `<div class="empty-state" style="grid-column:1/-1"><div class="empty-state-icon">🧪</div><h3>No A/B tests yet</h3><p>Create your first test to optimise workflow performance</p></div>`
        : tests.map(t => {
            const aRate = t.a_sent > 0 ? Math.round((t.a_opened / t.a_sent) * 100) : 0;
            const bRate = t.b_sent > 0 ? Math.round((t.b_opened / t.b_sent) * 100) : 0;
            const maxRate = Math.max(aRate, bRate, 1);
            return `
              <div class="ab-card">
                <div class="ab-card-header">
                  <div>
                    <div class="ab-card-name">${t.name}</div>
                    <div class="ab-card-wf">${t.workflow_id}</div>
                  </div>
                  <span class="pill ${t.status==='running'?'pill-amber':(t.status==='completed'?'pill-active':'pill-inactive')}">${t.status}</span>
                </div>
                <div class="ab-variants">
                  <div class="ab-variant">
                    <div class="ab-variant-label">Variant A ${t.winner==='A'?'🏆':''}</div>
                    <div class="ab-variant-text">${t.variant_a}</div>
                    <div class="ab-bar-wrap"><div class="ab-bar a" style="width:${Math.round((aRate/maxRate)*100)}%"></div></div>
                    <div class="ab-stat">${t.a_sent||0} sent · ${aRate}% open</div>
                  </div>
                  <div class="ab-variant">
                    <div class="ab-variant-label">Variant B ${t.winner==='B'?'🏆':''}</div>
                    <div class="ab-variant-text">${t.variant_b}</div>
                    <div class="ab-bar-wrap"><div class="ab-bar b" style="width:${Math.round((bRate/maxRate)*100)}%"></div></div>
                    <div class="ab-stat">${t.b_sent||0} sent · ${bRate}% open</div>
                  </div>
                </div>
                ${t.status === 'running' ? `
                  <div style="display:flex;gap:6px">
                    <button class="btn btn-sm btn-ghost w-full" onclick="declareWinner('${t.id}','A')">A wins</button>
                    <button class="btn btn-sm btn-ghost w-full" onclick="declareWinner('${t.id}','B')">B wins</button>
                  </div>
                ` : ''}
              </div>
            `;
          }).join('')
      }
    </div>
  `;
}

window.openNewAbModal = function() {
  openModal('New A/B Test',
    `<div class="form-group"><label>Test name *</label><input id="ab-name" type="text" placeholder="Cart Recovery Subject Lines"/></div>
     <div class="form-group"><label>Workflow ID *</label><input id="ab-wf" type="text" placeholder="C-01"/></div>
     <div class="form-group"><label>Variant A *</label><input id="ab-a" type="text" placeholder="You left something behind 🛒"/></div>
     <div class="form-group"><label>Variant B *</label><input id="ab-b" type="text" placeholder="Your cart misses you — 10% off inside"/></div>`,
    `<button class="btn btn-ghost" onclick="closeModal()">Cancel</button>
     <button class="btn btn-primary" onclick="doCreateAb()">Create test</button>`
  );
};

window.doCreateAb = async function() {
  const name = document.getElementById('ab-name').value.trim();
  const wf   = document.getElementById('ab-wf').value.trim();
  const a    = document.getElementById('ab-a').value.trim();
  const b    = document.getElementById('ab-b').value.trim();
  if (!name || !wf || !a || !b) { toast('All fields required', 'error'); return; }
  try {
    await api('POST', `/api/tenants/${state.slug}/ab-tests`, { name, workflow_id: wf, variant_a: a, variant_b: b });
    closeModal();
    toast('A/B test created', 'success');
    navTo('ab-tests');
  } catch (e) { toast(e.message, 'error'); }
};

window.declareWinner = async function(testId, winner) {
  try {
    await api('PATCH', `/api/tenants/${state.slug}/ab-tests/${testId}`, { winner });
    toast(`Variant ${winner} declared winner`, 'success');
    navTo('ab-tests');
  } catch (e) { toast(e.message, 'error'); }
};

// ═══════════════════════════════════════════════════
// VIEW: KNOWLEDGE BASE
// ═══════════════════════════════════════════════════
async function viewKnowledge(el) {
  const docs = await api('GET', `/api/tenants/${state.slug}/rag-docs`);
  const fmt  = (bytes) => bytes > 1e6 ? (bytes/1e6).toFixed(1)+'MB' : (bytes/1e3).toFixed(0)+'KB';

  el.innerHTML = `
    <div class="view-header">
      <div><div class="view-title">Knowledge Base</div><div class="view-sub">Documents powering your RAG Brain (S-02)</div></div>
    </div>
    <div class="rag-dropzone" id="rag-drop" onclick="document.getElementById('rag-file').click()">
      <div class="rag-dropzone-icon">📄</div>
      <div class="rag-dropzone-text">Drop files here or click to upload</div>
      <div class="rag-dropzone-sub">PDF, DOCX, TXT — max 50MB per file</div>
      <input id="rag-file" type="file" accept=".pdf,.docx,.txt" style="display:none" multiple onchange="handleRagUpload(event)"/>
    </div>
    <div class="rag-list">
      ${docs.length === 0
        ? '<div class="empty-state"><div class="empty-state-icon">🧠</div><h3>No documents yet</h3><p>Upload product manuals, FAQs, or guides</p></div>'
        : docs.map(d => `
            <div class="rag-item">
              <div class="rag-item-icon">${d.name.endsWith('.pdf') ? '📕' : d.name.endsWith('.docx') ? '📘' : '📄'}</div>
              <div class="rag-item-info">
                <div class="rag-item-name">${d.name}</div>
                <div class="rag-item-meta">${fmt(d.size_bytes)} · ${d.chunk_count || '?'} chunks · ${new Date(d.uploaded_at).toLocaleDateString()}</div>
              </div>
              <div class="rag-item-status">
                <span class="pill ${d.status==='indexed'?'pill-active':'pill-amber'}">${d.status}</span>
              </div>
              <button class="btn btn-danger btn-xs" onclick="deleteRagDoc('${d.id}','${d.name}')">Delete</button>
            </div>
          `).join('')}
    </div>
  `;

  // Drag-and-drop
  const dz = document.getElementById('rag-drop');
  dz.addEventListener('dragover', e => { e.preventDefault(); dz.classList.add('dragover'); });
  dz.addEventListener('dragleave', () => dz.classList.remove('dragover'));
  dz.addEventListener('drop', e => { e.preventDefault(); dz.classList.remove('dragover'); handleRagUpload({ target: { files: e.dataTransfer.files } }); });
}

window.handleRagUpload = async function(evt) {
  const files = Array.from(evt.target.files || []);
  for (const file of files) {
    try {
      await api('POST', `/api/tenants/${state.slug}/rag-docs`, { name: file.name, size_bytes: file.size });
      toast(`${file.name} uploaded — indexing in progress`, 'success');
    } catch (e) { toast(e.message, 'error'); }
  }
  navTo('knowledge');
};

window.deleteRagDoc = async function(docId, name) {
  if (!confirm(`Delete "${name}"? This cannot be undone.`)) return;
  try {
    await api('DELETE', `/api/tenants/${state.slug}/rag-docs/${docId}`);
    toast('Document deleted', 'success');
    navTo('knowledge');
  } catch (e) { toast(e.message, 'error'); }
};

// ═══════════════════════════════════════════════════
// VIEW: INTEGRATIONS
// ═══════════════════════════════════════════════════
async function viewIntegrations(el) {
  const ints = await api('GET', `/api/tenants/${state.slug}/integrations`);
  const connected = ints.filter(i => i.connected).length;
  el.innerHTML = `
    <div class="view-header">
      <div><div class="view-title">Integrations</div><div class="view-sub">${connected}/${ints.length} connected</div></div>
      <button class="btn btn-ghost btn-sm" onclick="openShopifyOauth()">+ Connect Shopify</button>
    </div>
    <div class="int-grid">
      ${ints.map(i => `
        <div class="int-card">
          <div class="int-card-header">
            <span class="int-label">${i.label}</span>
            <span class="int-dot ${i.connected ? 'ok' : 'err'}"></span>
          </div>
          <div class="int-env">${i.env_var}</div>
          <div class="int-wfs">Used by: ${Array.isArray(i.workflows) ? i.workflows.slice(0,3).join(', ')+(i.workflows.length>3?'…':'') : i.workflows}</div>
          ${!i.connected ? `<div style="margin-top:8px"><span class="pill pill-error">Not configured</span></div>` : ''}
        </div>
      `).join('')}
    </div>
  `;
}

window.openShopifyOauth = function() {
  const slug = state.slug;
  const shop = state.config?.store_url?.replace('https://','').replace('/','') || '';
  openModal('Connect Shopify',
    `<p class="text-sm text-muted mb-16">Enter your Shopify store domain to begin the OAuth flow.</p>
     <div class="form-group"><label>Shop domain</label><input id="shopify-domain" type="text" value="${shop}" placeholder="mystore.myshopify.com"/></div>`,
    `<button class="btn btn-ghost" onclick="closeModal()">Cancel</button>
     <button class="btn btn-primary" onclick="doShopifyOauth()">Connect →</button>`
  );
};

window.doShopifyOauth = function() {
  const shop = document.getElementById('shopify-domain').value.trim();
  if (!shop) { toast('Enter your shop domain', 'error'); return; }
  if (state.demo) { closeModal(); toast('Shopify OAuth flow would open here (demo mode)', 'info'); return; }
  window.location.href = `/api/shopify/install?shop=${encodeURIComponent(shop)}&slug=${encodeURIComponent(state.slug)}`;
};

// ═══════════════════════════════════════════════════
// VIEW: SETTINGS
// ═══════════════════════════════════════════════════
async function viewSettings(el) {
  const cfg = state.config || {};
  el.innerHTML = `
    <div class="view-header">
      <div><div class="view-title">Settings</div></div>
      <button class="btn btn-primary btn-sm" onclick="saveSettings()">Save changes</button>
    </div>
    <div class="card">
      <div class="card-title mb-16">Brand</div>
      <div class="settings-grid">
        <div class="form-group"><label>Brand name</label><input id="s-brand" type="text" value="${cfg.brand_name||''}"/></div>
        <div class="form-group"><label>Store URL</label><input id="s-url" type="text" value="${cfg.store_url||''}"/></div>
        <div class="form-group"><label>Brand voice</label><input id="s-voice" type="text" value="${cfg.brand_voice||''}"/></div>
        <div class="form-group"><label>Calendly URL</label><input id="s-cal" type="text" value="${cfg.calendly_url||''}"/></div>
      </div>
    </div>
    <div class="card">
      <div class="card-title mb-16">Contact emails</div>
      <div class="settings-grid">
        <div class="form-group"><label>Strategy email</label><input id="s-strat" type="email" value="${cfg.strategy_email||''}"/></div>
        <div class="form-group"><label>Ops email</label><input id="s-ops" type="email" value="${cfg.ops_email||''}"/></div>
        <div class="form-group"><label>CEO phone</label><input id="s-ceo" type="text" value="${cfg.ceo_phone||''}"/></div>
        <div class="form-group"><label>Support email</label><input id="s-sup" type="email" value="${cfg.support_email||''}"/></div>
      </div>
    </div>
    <div class="card">
      <div class="card-title mb-16">Thresholds</div>
      <div class="settings-grid">
        <div class="form-group"><label>Hot lead score</label><input id="s-lscore" type="number" value="${cfg.lead_hot_score_threshold||80}"/></div>
        <div class="form-group"><label>Churn risk threshold</label><input id="s-churn" type="number" value="${cfg.churn_risk_threshold||60}"/></div>
        <div class="form-group"><label>Free shipping (£)</label><input id="s-ship" type="number" value="${cfg.free_shipping_threshold||50}"/></div>
        <div class="form-group"><label>ROAS alert</label><input id="s-roas" type="number" value="${cfg.roas_alert_threshold||1.5}"/></div>
      </div>
    </div>
    <div class="card">
      <div class="card-title mb-16">Billing</div>
      <div style="display:flex;align-items:center;gap:16px">
        <div>
          <span class="fw-600">Current plan: </span>
          <span class="pill ${cfg.plan==='scale'?'pill-scale':cfg.plan==='enterprise'?'pill-enterprise':'pill-growth'}">${(cfg.plan||'growth').toUpperCase()}</span>
        </div>
        <button class="btn btn-ghost btn-sm" onclick="openBillingPortal()">Manage billing →</button>
      </div>
    </div>
    <div class="card">
      <div class="card-title mb-16">Client portal</div>
      <p class="text-sm text-muted mb-16">Generate a read-only access token to share your dashboard with clients.</p>
      <button class="btn btn-ghost btn-sm" onclick="generateClientToken()">Generate client access token</button>
      <div id="client-token-result" style="margin-top:12px"></div>
    </div>
  `;
}

window.saveSettings = async function() {
  const body = {
    brand_name:                document.getElementById('s-brand')?.value,
    store_url:                 document.getElementById('s-url')?.value,
    brand_voice:               document.getElementById('s-voice')?.value,
    calendly_url:              document.getElementById('s-cal')?.value,
    strategy_email:            document.getElementById('s-strat')?.value,
    ops_email:                 document.getElementById('s-ops')?.value,
    ceo_phone:                 document.getElementById('s-ceo')?.value,
    support_email:             document.getElementById('s-sup')?.value,
    lead_hot_score_threshold:  +document.getElementById('s-lscore')?.value || undefined,
    churn_risk_threshold:      +document.getElementById('s-churn')?.value || undefined,
    free_shipping_threshold:   +document.getElementById('s-ship')?.value  || undefined,
    roas_alert_threshold:      +document.getElementById('s-roas')?.value  || undefined,
  };
  try {
    const updated = await api('PUT', `/api/tenants/${state.slug}/config`, body);
    state.config = { ...state.config, ...updated };
    toast('Settings saved', 'success');
  } catch (e) { toast(e.message, 'error'); }
};

window.generateClientToken = async function() {
  try {
    const r = await api('POST', `/api/tenants/${state.slug}/client-access`);
    const link = `${window.location.origin}#client-token=${r.token}`;
    document.getElementById('client-token-result').innerHTML = `
      <div class="alert alert-info">
        <strong>Token generated (valid 30 days)</strong><br/>
        <small style="word-break:break-all">${r.token}</small><br/>
        <button class="btn btn-xs btn-ghost mt-8" onclick="navigator.clipboard.writeText('${r.token}').then(()=>toast('Copied!','success'))">Copy token</button>
      </div>
    `;
  } catch (e) { toast(e.message, 'error'); }
};

window.openBillingPortal = async function() {
  if (state.demo) { toast('Billing portal would open here (demo mode)', 'info'); return; }
  try {
    const r = await fetch('/api/billing/portal-session', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'x-api-key': state.key },
      body: JSON.stringify({ slug: state.slug }),
    });
    const data = await r.json();
    if (data.url) window.open(data.url, '_blank');
  } catch (e) { toast('Could not open billing portal', 'error'); }
};

// ═══════════════════════════════════════════════════
// MONTHLY REPORT
// ═══════════════════════════════════════════════════
window.openReport = function() {
  const month = new Date().toISOString().slice(0, 7);
  if (state.demo) {
    toast('Monthly report would open as a printable HTML page (demo mode)', 'info');
    return;
  }
  window.open(`/api/tenants/${state.slug}/reports/monthly?month=${month}&x-api-key=${encodeURIComponent(state.key)}`, '_blank');
};

// ═══════════════════════════════════════════════════
// CLIENT PORTAL
// ═══════════════════════════════════════════════════
async function enterClientPortal(token) {
  try {
    const r = await fetch(`/api/client/${token}/overview`);
    if (!r.ok) throw new Error('Invalid or expired token');
    const data = await r.json();
    document.getElementById('client-brand-name').textContent = data.brand_name || 'Your Brand';
    document.getElementById('client-dash-content').innerHTML = `
      <div class="stats-grid">
        <div class="stat-card"><div class="stat-value">${data.active_workflows}<span style="font-size:1rem;color:var(--text-3)">/24</span></div><div class="stat-label">Active workflows</div></div>
        <div class="stat-card green"><div class="stat-value">${data.hot_leads}</div><div class="stat-label">Hot leads this month</div></div>
        <div class="stat-card"><div class="stat-value">${data.carts_recovered}</div><div class="stat-label">Carts recovered</div></div>
        <div class="stat-card violet"><div class="stat-value">${(data.loyalty_points||0).toLocaleString()}</div><div class="stat-label">Loyalty points issued</div></div>
      </div>
      <div class="alert alert-info mt-16">This is a read-only client view. Contact your agency for full access.</div>
    `;
    showScreen('screen-client-dash');
  } catch (e) {
    document.getElementById('client-error').textContent = e.message;
    document.getElementById('client-error').style.display = 'block';
  }
}

// ═══════════════════════════════════════════════════
// AGENCY PORTAL
// ═══════════════════════════════════════════════════
async function enterAgencyPortal(key) {
  try {
    const r = await fetch('/api/agency/tenants', { headers: { 'x-agency-key': key } });
    if (!r.ok) throw new Error('Invalid agency key');
    const tenants = await r.json();
    state.agencyKey = key;
    renderAgencyDash(tenants);
    showScreen('screen-agency-dash');
  } catch (e) {
    document.getElementById('agency-error').textContent = e.message;
    document.getElementById('agency-error').style.display = 'block';
  }
}

function renderAgencyDash(tenants) {
  const grid = document.getElementById('agency-tenants-grid');
  if (!tenants.length) {
    grid.innerHTML = '<div class="empty-state"><div class="empty-state-icon">🏢</div><h3>No tenants yet</h3><p>Create your first client tenant to get started</p></div>';
    return;
  }
  grid.innerHTML = tenants.map(t => `
    <div class="agency-card">
      <div class="agency-card-header">
        <div>
          <div class="agency-card-name">${t.name}</div>
          <div class="agency-card-slug">/${t.slug}</div>
        </div>
        <span class="pill ${t.plan==='scale'?'pill-scale':t.plan==='enterprise'?'pill-enterprise':'pill-growth'}">${(t.plan||'growth').toUpperCase()}</span>
      </div>
      <div class="agency-card-stats">
        <div class="agency-stat"><div class="agency-stat-val">${t.active_workflows||0}</div><div class="agency-stat-lbl">Active WFs</div></div>
        <div class="agency-stat"><div class="agency-stat-val">${t.lead_count||0}</div><div class="agency-stat-lbl">Leads</div></div>
        <div class="agency-stat"><div class="agency-stat-val">${t.cart_recoveries||0}</div><div class="agency-stat-lbl">Recovered</div></div>
      </div>
      <div class="agency-card-footer">
        <span class="text-xs text-muted">Last activity: ${t.last_activity ? new Date(t.last_activity).toLocaleDateString() : 'Never'}</span>
      </div>
    </div>
  `).join('');
}

window.openNewTenantModal = function() {
  openModal('New tenant',
    `<div class="form-group"><label>Brand name *</label><input id="nt-brand" type="text" placeholder="Luna Cosmetics"/></div>
     <div class="form-group"><label>Slug *</label><input id="nt-slug" type="text" placeholder="luna-cosmetics"/></div>
     <div class="form-group"><label>Plan</label><select id="nt-plan"><option value="growth">Growth</option><option value="scale">Scale</option><option value="enterprise">Enterprise</option></select></div>`,
    `<button class="btn btn-ghost" onclick="closeModal()">Cancel</button>
     <button class="btn btn-primary" onclick="doCreateTenant()">Create tenant</button>`
  );
};

window.doCreateTenant = async function() {
  const name = document.getElementById('nt-brand').value.trim();
  const slug = document.getElementById('nt-slug').value.trim();
  const plan = document.getElementById('nt-plan').value;
  if (!name || !slug) { toast('Name and slug required', 'error'); return; }
  try {
    await fetch('/api/agency/tenants', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'x-agency-key': state.agencyKey },
      body: JSON.stringify({ name, slug, plan }),
    });
    closeModal();
    toast('Tenant created', 'success');
    // Refresh
    const r = await fetch('/api/agency/tenants', { headers: { 'x-agency-key': state.agencyKey } });
    renderAgencyDash(await r.json());
  } catch (e) { toast(e.message, 'error'); }
};

// ═══════════════════════════════════════════════════
// ONBOARDING
// ═══════════════════════════════════════════════════
let obStep = 1;
const OB_STEPS = 4;

function obNav(dir) {
  const newStep = obStep + dir;
  if (newStep < 1 || newStep > OB_STEPS) return;
  document.getElementById(`onboard-section-${obStep}`).classList.remove('active');
  document.querySelectorAll('.step').forEach(el => {
    const s = +el.dataset.step;
    el.classList.toggle('active', s === newStep);
    el.classList.toggle('done', s < newStep);
  });
  obStep = newStep;
  document.getElementById(`onboard-section-${obStep}`).classList.add('active');
  document.getElementById('ob-back').style.display = obStep > 1 ? 'inline-flex' : 'none';
  document.getElementById('ob-next').textContent = obStep === OB_STEPS ? 'Create tenant →' : 'Next →';
}

async function obSubmit() {
  const brand = document.getElementById('ob-brand').value.trim();
  const slug  = document.getElementById('ob-slug').value.trim();
  if (!brand || !slug) {
    document.getElementById('onboard-error').textContent = 'Brand name and slug are required';
    document.getElementById('onboard-error').style.display = 'block';
    return;
  }
  const payload = {
    brand_name: brand,
    slug,
    plan:       document.getElementById('ob-plan').value,
    store_url:  document.getElementById('ob-url').value,
    strategy_email: document.getElementById('ob-strat').value,
    ops_email:  document.getElementById('ob-ops').value,
    ceo_phone:  document.getElementById('ob-ceo').value,
    calendly_url: document.getElementById('ob-cal').value,
    brand_voice: document.getElementById('ob-voice').value,
    free_shipping_threshold: +document.getElementById('ob-ship').value || 50,
    lead_hot_score_threshold: +document.getElementById('ob-lscore').value || 80,
    churn_risk_threshold: +document.getElementById('ob-churn').value || 60,
    slack_channel_leads: document.getElementById('ob-sl-leads').value,
    slack_channel_hot_leads: document.getElementById('ob-sl-hot').value,
    slack_channel_outreach: document.getElementById('ob-sl-out').value,
    slack_channel_crm: document.getElementById('ob-sl-crm').value,
    slack_channel_support: document.getElementById('ob-sl-sup').value,
    slack_channel_revenue: document.getElementById('ob-sl-rev').value,
  };
  try {
    const btn = document.getElementById('ob-next');
    btn.disabled = true; btn.textContent = 'Creating…';
    const result = await fetch('/api/onboard', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'x-api-key': state.key || document.getElementById('inp-key').value },
      body: JSON.stringify(payload),
    });
    if (!result.ok) throw new Error((await result.json()).error || 'Onboard failed');
    toast('Tenant created! Connecting…', 'success');
    await connect(slug, state.key || document.getElementById('inp-key').value);
    showScreen('screen-app');
  } catch (e) {
    document.getElementById('onboard-error').textContent = e.message;
    document.getElementById('onboard-error').style.display = 'block';
    document.getElementById('ob-next').disabled = false;
    document.getElementById('ob-next').textContent = 'Create tenant →';
  }
}

// ═══════════════════════════════════════════════════
// EVENT LISTENERS — init
// ═══════════════════════════════════════════════════
document.addEventListener('DOMContentLoaded', () => {

  // Check for client portal token in hash
  const hash = window.location.hash;
  if (hash.startsWith('#client-token=')) {
    const token = hash.slice('#client-token='.length);
    showScreen('screen-client');
    document.getElementById('inp-client-token').value = token;
    return;
  }

  // ── Connect screen ──
  document.getElementById('btn-connect').addEventListener('click', async () => {
    const slug = document.getElementById('inp-slug').value.trim();
    const key  = document.getElementById('inp-key').value.trim();
    const err  = document.getElementById('connect-error');
    err.style.display = 'none';
    if (!slug || !key) { err.textContent = 'Slug and API key are required'; err.style.display = 'block'; return; }
    const btn = document.getElementById('btn-connect');
    btn.disabled = true; btn.textContent = 'Connecting…';
    try {
      await connect(slug, key);
    } catch (e) {
      err.textContent = e.message.includes('404') ? 'Tenant not found — check your slug' : (e.message.includes('401') ? 'Invalid API key' : e.message);
      err.style.display = 'block';
      // If tenant not found, offer onboarding
      if (e.message.includes('404')) {
        err.innerHTML += '<br/><a href="#" onclick="startOnboard()">→ Create this tenant</a>';
      }
    } finally {
      btn.disabled = false; btn.textContent = 'Connect';
    }
  });

  document.getElementById('inp-key').addEventListener('keydown', e => { if (e.key === 'Enter') document.getElementById('btn-connect').click(); });

  document.getElementById('btn-demo').addEventListener('click', connectDemo);

  document.getElementById('link-client').addEventListener('click', e => { e.preventDefault(); showScreen('screen-client'); });
  document.getElementById('link-agency').addEventListener('click', e => { e.preventDefault(); showScreen('screen-agency'); });

  document.getElementById('link-back-from-client').addEventListener('click', e => { e.preventDefault(); showScreen('screen-connect'); });
  document.getElementById('link-back-from-agency').addEventListener('click', e => { e.preventDefault(); showScreen('screen-connect'); });

  // ── Client portal login ──
  document.getElementById('btn-client-login').addEventListener('click', async () => {
    const token = document.getElementById('inp-client-token').value.trim();
    if (!token) { document.getElementById('client-error').textContent = 'Token required'; document.getElementById('client-error').style.display = 'block'; return; }
    await enterClientPortal(token);
  });

  // ── Agency portal login ──
  document.getElementById('btn-agency-login').addEventListener('click', async () => {
    const key = document.getElementById('inp-agency-key').value.trim();
    if (!key) { document.getElementById('agency-error').textContent = 'API key required'; document.getElementById('agency-error').style.display = 'block'; return; }
    await enterAgencyPortal(key);
  });

  // ── App nav ──
  document.querySelectorAll('.nav-item[data-view]').forEach(el => {
    el.addEventListener('click', e => { e.preventDefault(); navTo(el.dataset.view); });
  });

  document.getElementById('btn-signout').addEventListener('click', signOut);
  document.getElementById('btn-report').addEventListener('click', openReport);

  // ── Onboarding ──
  document.getElementById('ob-next').addEventListener('click', () => {
    if (obStep === OB_STEPS) obSubmit();
    else obNav(1);
  });
  document.getElementById('ob-back').addEventListener('click', () => obNav(-1));

  // ── Agency portal new tenant ──
  document.getElementById('btn-agency-new-tenant').addEventListener('click', openNewTenantModal);
  document.getElementById('btn-agency-signout').addEventListener('click', () => {
    state.agencyKey = null;
    showScreen('screen-connect');
  });

  // ── Modal close ──
  document.getElementById('modal-close').addEventListener('click', closeModal);
  document.getElementById('modal').addEventListener('click', e => { if (e.target.id === 'modal') closeModal(); });
});

// Expose for inline onclicks
window.closeModal = closeModal;
window.openReport = openReport;
window.navTo = navTo;
window.startOnboard = function() { showScreen('screen-onboard'); };
